services:
  orm:
    build: 
      context: .
      args:
        - DATABASE_URL=postgres://postgres:test_pass@db:5432/test_db
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "test_pass"
      POSTGRES_DB: "test_db"
    ports: 
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
